name: Update
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Clone data
        run: git clone --depth 1 https://github.com/sociedatos/bo-combustible.git saldos

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update
        run: |
          mkdir reporte
          python timeline.py

      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reporte
          force_orphan: true
          user_name: reportecombustibles-bot
          user_email: reportecombustibles-bot@example.com